version: '2'
services:
  envoy:
    image: envoy:v1
    build:
      context: .
      dockerfile: envoy/Dockerfile
    ports:
        - "80:10000"
    tty: true
    networks:
      - envoy

  nginx:
    image: front:v1
    build:
      context: .
      dockerfile: centos7-envoy/Dockerfile
    #  - [docker-compose up したコンテナを起動させ続ける方法 - Qiita](https://qiita.com/sekitaka_1214/items/2af73d5dc56c6af8a167)
   expose: 
     - "8080"
   tty: true
   networks:
     - envoy
     - app

networks:
  envoy:
  app:
