version: '2'
services:
  envoy:
    container_name: envoy
    image: envoy:v1
    build:
      context: .
      dockerfile: ./envoy/Dockerfile
    ports:
        - "80:10000"
    tty: true
    volumes:
      - ./envoy/config:/opt/envoy/config
    networks:
      - front
      - back

  # request front:8080 remap to envoy:9000
  front:
    container_name: front
    image: front:v1
    build:
      context: .
      dockerfile: ./front/Dockerfile
    expose: 
      - "8080"
    tty: true
    networks:
      - front
    environment:
      FRONT_PROXY_DESTINATION: http://envoy:9000
      FRONT_PORT: 8080

  app1:
    container_name: app1
    image: app:v1
    build:
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    networks:
      - back
    expose:
        - "8081"
    environment:
      APP_PORT: 8081
      APP_TEXT: "I am app1"

  app2:
    container_name: app2
    image: app:v1
    build:
      context: .
      dockerfile: ./app/Dockerfile
    tty: true
    networks:
      - back
    expose:
        - "8082"
    environment:
      APP_PORT: 8082
      APP_TEXT: "I am app2"

networks:
  front:
  back:
