@startuml
title envoy

'==============================
' Setting
'==============================
left to right direction
skinparam handwritten true


actor Mac as Mac

package SidecarUnit as SidecarUnitFront {
  node envoy-front <<container>> as EnvoyFront {
    component "listener-config" <<yaml>> as ListenerConfigFront
    note top of ListenerConfigFront 
      Downstreamに対する設定
    end note
    
    component "cluster-config" <<yaml>> as ClusterConfigFront
    note bottom of ClusterConfigFront 
      Upstreamに対する設定
    end note    
  }
  node front <<container>> as Front
}

package SidecarUnit as SidecarUnitApp {
  node envoy-app <<container>> as EnvoyApp {
    component "listener-config" <<yaml>>  as ListenerConfigApp
    component "cluster-config" <<yaml>> as ClusterConfigApp
  }
  node app <<container>> as App
}

Mac --> ListenerConfigFront : <<Downstream>>
ListenerConfigFront -> ClusterConfigFront

ClusterConfigFront --> Front : <<Upstream>>
ListenerConfigFront <-- Front : <<Downstream>>

ClusterConfigFront -> ListenerConfigApp : envoy-frontからみると<b><<Upstream>></b>\nenvoy-appからみると<b><<Downstream>></b>

ListenerConfigApp -> ClusterConfigApp
ClusterConfigApp --> App : <<Upstream>>


'------------
' layout


'------------
' referenses

' > Application Instance Identity and Intro to Envoy in PCF  
' > https://gist.github.com/nikhilsuvarna/bd0aa0ef01880270c13d145c61a4af22#envoy

@enduml
