@startuml
title structure

'==============================
' Setting
'==============================
left to right direction
skinparam handwritten true

actor User

node Mac as Mac {
   component ":80" as MacInputPort
}
node "envoy" <<container>> as EnvoyFront {
   component ":10000" as EnvoyFrontInputPort1
   component ":9000" as EnvoyFrontInputPort2
}
node front <<container>> as Front {
   component ":8080" as FrontInputPort
}
node app1 <<container>> as App1 {
   component ":8081" as App1InputPort
}
node app2 <<container>> as App2 {
   component ":8082" as App2InputPort
}

User --> MacInputPort
MacInputPort --> EnvoyFrontInputPort1
EnvoyFrontInputPort1 --> FrontInputPort
FrontInputPort --> EnvoyFrontInputPort2

EnvoyFrontInputPort2 --> App1InputPort
EnvoyFrontInputPort2 --> App2InputPort


'------------
' layout


'------------
' referenses

' > Application Instance Identity and Intro to Envoy in PCF  
' > https://gist.github.com/nikhilsuvarna/bd0aa0ef01880270c13d145c61a4af22#envoy

@enduml
